[package]
name = "osaka-dns"
version = "0.1.2"
authors = ["Arvid E. Picciani <aep@exys.org>"]
description = "async for rust without the noise"
license     = "MIT/Apache-2.0"
repository  = "https://github.com/aep/osaka"
documentation = "https://docs.rs/osaka-dns"

[dependencies]
#osaka = "0.1.1"
osaka = {path = "../osaka"}
